import type { NextPage } from "next";
import Head from "next/head";
import { Navbar } from "../components/Navbar";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Rowdy Creators</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="h-screen bg-rc-darkblue">
				<Navbar />
				<h1 className="text-xl">Hello world!</h1>
			</div>
		</>
	);
};

export default Home;

type TechnologyCardProps = {
	name: string;
	description: string;
	documentation: string;
};
